BUILD.bazel, WORKSPACE, deps.bzl, doc/BUILD.bazel, lib/BUILD.bazel, rules/BUILD.bazel, tests/BUILD.bazel
- Added `rules_bzlformat` and updated all packages to include `bzlformat_pkg`.
=> Add rules_bzlformat

.github/workflows/ci.yaml, .github/workflows/release.yml, lib/private/fail.sh, lib/private/git.sh, tools/BUILD.bazel, tools/create_release.sh, tools/generate_release_notes.sh
Related to #4.
- Implemented `create_release.sh`.
- Refactored `fail()` to accept multiple args separating each by a newline in the output.
- Added `usage_error` and `show_usage` to `fail.sh`.
=> Implemented `create_release` and fixed bug with create_release.yml reference.

.github/workflows/release.yml, lib/private/github.sh, tools/BUILD.bazel, tools/create_release.sh
=> Added release check to `create_release` and `worfklow_dispatch` event to `release.yml`.

.github/workflows/create_release.yml, .github/workflows/release.yml
=> Add `workflow_dispatch` to `create_release.yml`

.github/actions/update_readme/action.yml, .github/workflows/create_release.yml, release/README.md
=> Documented the release process and fixed defaults in release workflows and actions.

shlib/lib/arrays.sh, tests/shlib_tests/lib_tests/arrays_tests/BUILD.bazel, tests/shlib_tests/lib_tests/arrays_tests/double_quote_items_test.sh, tests/shlib_tests/lib_tests/arrays_tests/join_by_test.sh
- Add `double_quote_items`.
- Add support for multi-character delimiters to `join_by`.
=> Updates to `arrays.sh`: add `double_quote_items`, add support multi-character delimiters to `join_by`

deps.bzl
=> Updated to keith/buildifier-prebuilt 0.2.0.

examples/markdown/simple/.bazelrc
Added .bazelrc with settings that will output detailed info about failures. Trying to debug [this failure](https://github.com/cgrindel/bazel-starlib/runs/5139869439?check_suite_focus=true).
=> Added .bazelrc to examples/markdown/simple.

doc/markdown/rules_and_macros_overview.md, markdown/defs.bzl, markdown/private/markdown_generate_toc.bzl, tests/markdown_tests/markdown_generate_toc_tests/BUILD.bazel, tests/markdown_tests/markdown_generate_toc_tests/expected_structured.md, tests/markdown_tests/markdown_generate_toc_tests/expected_structured_custom_toc_header.md, tests/markdown_tests/markdown_generate_toc_tests/expected_structured_keep_toc_header_entry.md, tests/markdown_tests/markdown_generate_toc_tests/expected_structured_no_toc_header.md, tests/markdown_tests/markdown_generate_toc_tests/structured.md, tests/markdown_tests/markdown_generate_toc_tests/structured_custom_toc_header.md, tests/markdown_tests/markdown_generate_toc_tests/structured_no_toc_header.md
Related to #86.
- Implemented `markdown_generate_toc` build rule and tests.
=> Implemented `markdown_generate_toc` build rule and tests.

bzlrelease/README.md
=> Updated bzlrelease documentation with info on configuring auto-merge and automatic head branch deletion.

deps.bzl
=> Upgraded keith/buildifier-prebuilt to 0.3.2.

markdown/private/markdown_register_node_deps.bzl
=> Added node_repositories declaration with node and yarn versions to address warnings.

WORKSPACE
=> Upgrade rules_bazel_integration_test to 0.7.0

bzllib/BUILD.bazel, bzllib/defs.bzl, bzllib/private/BUILD.bazel, bzllib/private/bazel_labels.bzl, bzllib/private/workspace_name_resolvers.bzl, tests/bzllib_tests/bazel_labels_tests/BUILD.bazel, tests/bzllib_tests/bazel_labels_tests/normalize_tests.bzl, tests/bzllib_tests/bazel_labels_tests/parse_tests.bzl
Originally implemented in [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj/blob/main/xcodeproj/internal/bazel_labels.bzl).
=> feat: add bazel_labels to bzllib

.bcr/source.template.json, MODULE.bazel
=> fix: set `MODULE.bazel` version to 0.0.0 and fix download URL

.bcr/metadata.template.json
=> fix: update metadata for BCR to include OWNER and REPO

bzlformat/tools/buildifier.sh
=> chore: more debug for buildifier.sh

.github/actions/configure_remote_cache_auth/action.yml, .github/workflows/ci.yml, shared.bazelrc
=> chore: configure remote bazel cache

ci.bazelrc
=> chore: remove disk cache for CI

.bcr/presubmit.yml
=> chore: sync BCR presubmit version with `.bazelversion`

BUILD.bazel, MODULE.bazel, bzlrelease/tools/BUILD.bazel, bzlrelease/tools/create_release_tag.sh, bzlrelease/tools/generate_gh_changelog.sh, bzlrelease/tools/generate_git_archive.sh, shlib/lib/BUILD.bazel, shlib/lib/git.sh, tests/bzlrelease_tests/tools_tests/generate_gh_changelog_test.sh, tests/bzlrelease_tests/tools_tests/generate_git_archive_test.sh, tests/bzlrelease_tests/tools_tests/generate_release_notes_test.sh, tests/shlib_tests/lib_tests/git_tests/BUILD.bazel, tests/shlib_tests/lib_tests/git_tests/git_integration_test.sh, tests/tools_tests/git_tests/BUILD.bazel, tests/tools_tests/git_tests/git_binary_test.sh, tests/tools_tests/git_tests/git_vars_test.sh, tools/git/BUILD.bazel, tools/git/extensions.bzl, tools/git/git_binary.bzl, tools/git/git_toolchain.bzl, tools/git/git_toolchains.bzl, tools/git/git_vars.bzl, tools/git/local_git.bzl
Refactor all but the bzltidy stuff to use the toolchain.
=> feat: add `git` toolchain

.editorconfig, .github/workflows/ci.yml, bzlrelease/tools/generate_gh_changelog.sh, shlib/lib/github.sh, tests/shlib_tests/lib_tests/github_tests/BUILD.bazel, tests/shlib_tests/lib_tests/github_tests/get_gh_changelog_organized_test.sh
=> feat: organize change log in release notes

.github/workflows/ci.yml, MODULE.bazel
=> fix: disable last_green integration tests

tests/shlib_tests/lib_tests/github_tests/get_gh_changelog_organized_test.sh
=> fix: update expected for get_gh_changelog_organized_test
