.github/workflows/bazel.yml, BUILD.bazel, deps.bzl
Closes #5.
- Updated rules_bzlformat to 0.2.0.
- Added Ubuntu CI runner.
=> Updated rules_bzlformat to 0.2.0

.github/workflows/bazel.yml, BUILD.bazel, lib/private/BUILD.bazel, lib/private/env.sh, lib/private/git.sh, lib/private/github.sh, tests/BUILD.bazel, tests/integration_test_common.bzl, tests/lib_tests/private_tests/github_tests/BUILD.bazel, tests/lib_tests/private_tests/github_tests/generate_gh_changelog_test.sh, tests/lib_tests/private_tests/github_tests/get_gh_api_base_url_test.sh, tests/lib_tests/private_tests/github_tests/get_gh_auth_status_test.sh, tests/lib_tests/private_tests/github_tests/get_gh_auth_token_test.sh, tests/lib_tests/private_tests/github_tests/get_gh_changelog_test.sh, tests/lib_tests/private_tests/github_tests/get_gh_repo_name_test.sh, tests/lib_tests/private_tests/github_tests/get_gh_repo_owner_test.sh, tests/lib_tests/private_tests/github_tests/get_gh_username_test.sh, tests/lib_tests/private_tests/github_tests/is_github_repo_url_test.sh, tests/setup_git_repo.sh, tests/tools_tests/BUILD.bazel, tests/tools_tests/generate_gh_changelog_test.sh, tests/tools_tests/generate_sha256_test.sh, tools/BUILD.bazel, tools/generate_gh_changelog.sh, tools/generate_sha256.sh, tools/get_gh_auth_token.sh
Related to #4.
- Added `git.sh`, `github.sh`, and `env.sh` to house shell libraries used by the changelog generation.
- Implemented `@cgrindel_bazel_starlib//tools:generate_gh_changelog` to retrieve a changelog from the Github API.
- Added integration tests to test the changelog generation functionality.
- Updated the sha256 generation script to look for `shasum` instead of `sha256sum`.
=> Generate a changelog using Github API

lib/private/assertions.sh, tests/lib_tests/private_tests/assertions_tests/BUILD.bazel, tests/lib_tests/private_tests/assertions_tests/assert_equal_test.sh, tests/lib_tests/private_tests/assertions_tests/assert_fail.sh, tests/lib_tests/private_tests/assertions_tests/assert_match_test.sh, tests/lib_tests/private_tests/assertions_tests/assert_no_match_test.sh
- Added `assert_match` and `assert_no_match`. They are used to test for patterns in strings.
- Refactored the error message logic into its own.
- Added tests for `assert_equal`, `assert_match`, and `assert_no_match`.
=> Added `assert_match` and `assert_no_match`.

BUILD.bazel, README.md, doc/BUILD.bazel, doc/generate_release_notes.md, doc/rules.md, doc/update_readme.md, lib/BUILD.bazel, rules/BUILD.bazel, rules/private/BUILD.bazel, rules/private/execute_binary.bzl, rules/private/generate_release_notes.bzl, rules/private/update_readme.bzl, rules/update_readme.bzl, tests/rules_tests/update_readme_tests/BUILD.bazel, tests/rules_tests/update_readme_tests/update_readme_test.sh, tests/rules_tests/update_readme_tests/workspace_snippet.tmpl, tests/tools_tests/BUILD.bazel, tests/tools_tests/generate_fake_snippet.sh, tests/tools_tests/update_readme_test.sh, tools/BUILD.bazel, tools/generate_workspace_snippet.sh, tools/update_readme.sh
Related to #4.
- Implemented `update_readme.sh` and `update_readme` macro. They are used to update a `README.md` file with an updated workspace snippet.
- Fixed file args resolution for `execute_binary`. Now, they resolve from the `RUNFILES_DIR`.
- Removed obsolete `rules_pkg` declarations.
=> Implemented `update_readme.sh` and `update_readme` macro

.github/actions/update_readme/action.yml, .github/workflows/create_release.yml, .github/workflows/update_readme.yml
Related to #4.
- Initial, untested version of the workflow. (Need to add it before it can be seen and tested on another branch.
- Update the create_release.yml to use setup_bazel_cache and setup_bazel actions.
=> Added update_readme.yml Github Actions workflow

.github/actions/update_readme/action.yml, .github/workflows/ci.yaml, .github/workflows/update_readme.yml
Related to #4.
- Added steps to create a PR and auto-merge the PR.
- Added input parameter `base_branch` to update README.md workflow and action.
- Updated CI to build and test for `test_main` branch as well as `main`.
=> Added PR creation and automerge when updating README.md

.github/workflows/update_readme.yml
Closes #4.
Using the app-generated token allows the auto-created PRs to trigger the CI workflow.
=> Updated update_readme workflow to use app-generated token

.github/workflows/create_release.yml, tools/BUILD.bazel, tools/create_release.sh, tools/create_release_tag.sh
Related to #4.
- Add `create_release.sh` utility that launches the `create_release.yml` GA workflow.
- Removed `required` designation for inputs.
=> Add `create_release.sh` utility that launches the `create_release.yml` GA workflow.

BUILD.bazel, bazeldoc/private/BUILD.bazel, bazeldoc/private/doc_for_provs.bzl, bazeldoc/private/update_doc.bzl, bazeldoc/private/write_file_list.bzl, doc/bazeldoc/BUILD.bazel, doc/bazeldoc/api.md, doc/bazeldoc/build_rules_overview.md, doc/bazeldoc/doc_utilities.md, doc/bzlformat/BUILD.bazel, doc/bzllib/BUILD.bazel, doc/bzllib/api.md, doc/bzllib/rules.md, doc/bzlrelease/BUILD.bazel, doc/bzlrelease/rules.md, doc/shlib/BUILD.bazel, doc/updatesrc/BUILD.bazel
Closes #43.
- Updated `update_doc` to use `updatesrc_update`.
- Removed `doc_path` attribute in `bazeldoc` macros.
- Generate documentation for all `bazeldoc` macros and libraries.
=> Update `bazeldoc` to use `updatesrc_update`

examples/updatesrc/simple/header/BUILD.bazel, examples/updatesrc/simple/header/header.sh, examples/updatesrc/simple/srcs/Bar/BUILD.bazel, examples/updatesrc/simple/srcs/Bar/c.txt, examples/updatesrc/simple/srcs/Bar/d.txt
Closes #51.
- Updated updatesrc's simple example so that it does not pollute the workspace directory.
- Updated one of the simple example packages to use `updatesrc_diff_and_update`.
=> Updated updatesrc's simple example so that it does not pollute the workspace directory.

README.md, bazeldoc/README.md, bzlformat/README.md, release/workspace_snippet.tmpl
- Add missing load statement to bzlformat `README.md`.
- Removed `stardoc` refs from `bazel-starlib` workspace config.
- Added `stardoc` ref to `bazeldoc` documentation.
=> Fixed issues with documentation for `bazel-starlib`, `bzlformat`, `bazeldoc`.

BUILD.bazel
Closes #52.
- It turns out that the `targets_to_run` target executes before the update commands.
=> Added `@cgrindel_rules_bazel_integration_test//tools:update_deleted_packages` to update_all.

examples/markdown/simple/BUILD.bazel, markdown/private/markdown_check_links_test.bzl
Closes #85 .
- Bazel 4.2.2 does not support `runfiles.merge_all`. Since we were only merging one runfiles object, I switched it to `runfiles.merge`.
=> Changed call to runfiles `merge_all` to `merge`.

.github/workflows/ci.yml, examples/markdown/BUILD.bazel, examples/markdown/simple/BUILD.bazel, examples/markdown/simple/tests/BUILD.bazel, tests/repo_markdown_tests/BUILD.bazel
Related to #108.
- Tag `markdown_check_links_test` as `exclusive` to avoid failure on MacOS CI machines. The tests tend to fail on the GitHub-hosted MacOS runners.
- Disable the markdown integration test for now.
- Scheduled the CI to run every hour.
=> Tag `markdown_check_links_test` as `exclusive` to avoid failure on MacOS CI machines.

bzlrelease/private/generate_workspace_snippet.bzl, bzlrelease/tools/generate_workspace_snippet.sh, doc/bzlrelease/generate_workspace_snippet.md, tests/bzlrelease_tests/rules_tests/generate_release_notes_tests/BUILD.bazel, tests/bzlrelease_tests/rules_tests/generate_release_notes_tests/generate_release_notes_test.sh, tests/bzlrelease_tests/tools_tests/generate_workspace_snippet_test.sh
Closes #106.
- Added `workspace_name` to `generate_workspace_name.bzl`.
- Added tests confirming that the customization works correctly in `generate_workspace_snippet.sh` and that it carries through to dependent tasks.
=> Allow for a custom workspace name in generated workspace snippets.

BUILD.bazel, README.md, doc/markdown/BUILD.bazel, doc/markdown/rules_and_macros_overview.md, examples/markdown/simple/BUILD.bazel, examples/markdown/simple/README.md, examples/markdown/simple/WORKSPACE, examples/markdown/simple/bar/BUILD.bazel, examples/markdown/simple/tests/BUILD.bazel, markdown/defs.bzl, markdown/private/markdown_pkg.bzl, tests/markdown_tests/BUILD.bazel, tests/repo_markdown_tests/BUILD.bazel
Closes #86.
- Implemented `markdown_pkg` macro to define targets for TOC generation, a `diff_test` to confirm that the markdown files are up-to-date, an update target to copy the generated files to the source directory, and a `filegroup` that is useful for collecting files for link check tests.
- Updated the `examples/markdown/simple` example to use `markdown_pkg`.
- Updated the root of the parent workspace to use `markdown_pkg`.
=> Implemented `markdown_pkg` to aid in the maintenance of markdown files.

markdown/private/README.md, markdown/private/package.json, markdown/private/yarn.lock
- Added `README.md` describing how to perform the updates.
- Updated the declared version for `markdown-link-check` to 3.10.0.
=> Upgrade markdown-link-check 3.10.0

.github/workflows/create_release.yml, bazel_versions.bzl, release/BUILD.bazel
- Update `bazel_versions.bzl`.
- Fix release workspace snippet to use the archive SHA256.
Related to #200.
=> chore: point to `gha_create_release@v2`

README.md, doc/README.md, release/README.md
- Add TOC entries for `bzltidy`.
- Update release doc mentioning the creation of the release archive.
=> fix: add links to `bzltidy` documentation

WORKSPACE
Related to bazelbuild/bazel-skylib#431
=> chore: point to merge of bazel-skylib PR

.bcr/source.template.json, BUILD.bazel, examples/BUILD.bazel
- Add the E2E test in the release archive.
- Set the `strip-prefix` to an empty string. We do not have a prefix to be stripped in our release archive.
- Remove git stuff.
Related to #195.
=> fix: include `examples/bzlmod_e2e` in release archive

examples/bzlmod_e2e/.bazelrc
=> fix: use minimal .bazelrc in `bzlmod_e2e` workspace

bzlformat/tools/buildifier.sh
Trying to debug [error on BCR CI machines](https://buildkite.com/bazel/bcr-presubmit/builds/1101#0186c91f-7ac0-4d98-8f29-2a9e4623948e).
Related to #195.
=> chore: add debug code to `buildifier.sh`

bzlformat/tools/buildifier.sh
=> chore: add more debug code to `buildifier.sh`

MODULE.bazel, bzlformat/tools/buildifier.sh
- Remove debug code in `buildifier.sh`.
Related to #195.
=> chore: add `bazel_compatibility` to module

.github/actions/configure_bzlmod/action.yml, BUILD.bazel, bazeldoc/private/doc_for_provs.bzl, bazeldoc/private/stardoc_for_prov.bzl, bzllib/tests/rules_tests/filter_srcs_tests.bzl, bzlmod/BUILD.bazel, doc/bazeldoc/BUILD.bazel, doc/bazeldoc/build_rules_overview.md, doc/bzlformat/BUILD.bazel, doc/bzllib/BUILD.bazel, doc/bzlrelease/BUILD.bazel, doc/bzltidy/BUILD.bazel, doc/shlib/BUILD.bazel, doc/updatesrc/BUILD.bazel, doc/updatesrc/rules_and_macros_overview.md, examples/BUILD.bazel, examples/bzlformat/BUILD.bazel, examples/markdown/BUILD.bazel, examples/updatesrc/BUILD.bazel, shared.bazelrc, updatesrc/private/update_all.sh, updatesrc/private/updatesrc_diff_and_update.bzl
- Add `//bzlmod:enabled` flag.
- Add `//bzlmod:is_enabled` config setting.
- Mark stardoc rule generation as being incompatible with bzlmod.
- Added Gazelle directives to ignore child workspaces.
- Enable bzlmod by default in `shared.bazelrc`.
- Uncommented the doc generation build files.
Related to #195.
=> chore: mark stardoc doc generation targets as incompatible with bzlmod

bazeldoc/private/stardoc_for_prov.bzl
I forgot to enable doc generation when I updated stardoc to 0.5.6.
=> chore: enable doc generation with bzlmod enabled.

BUILD.bazel, MODULE.bazel, cmd/go_deps/README.md
[Related thread](https://github.com/bazelbuild/bazel-central-registry/pull/752#discussion_r1254980477)
`rules_go` now provides access to the Go binary at `@rules_go//go`.
cc: @fmeum
=> chore: remove obsolete go_sdk references

shared.bazelrc, tests/bzltidy_tests/tidy_all_test.sh
- Sort the output of `find_tidy_out_files`.
- Update the expected positions for the tidy out files.
=> fix: failing tidy_all test failure in CI

.github/renovate.json
The self-hosted Renovate instance is running in a container that includes Bazelisk.
=> chore: remove bazelisk install from Renovate post upgrade commands

bzlformat/tools/missing_pkgs/find.sh, bzltidy/private/check_tidy.sh, bzltidy/private/tidy.sh, bzltidy/private/tidy_all.sh, updatesrc/private/update_all.sh
We could be executed in [Bazel integration tests](https://github.com/bazel-contrib/rules_bazel_integration_test). Be sure to use the Bazel binary specified by the tests, if it is present. Otherwise, use `bazel`.
=> fix: use the correct Bazel binary

tests/bzltidy_tests/workspace/MODULE.bazel.lock, tests/bzltidy_tests/workspace/child_workspaces/bar/MODULE.bazel.lock, tests/bzltidy_tests/workspace/child_workspaces/foo/MODULE.bazel.lock
The test is failing because the lock files were not up-to-date.
=> fix: update lock files for `bzltidy` test

.github/workflows/ci.yml, BUILD.bazel, tests/bzltidy_tests/BUILD.bazel, tests/bzltidy_tests/tidy_all_test.sh, tests/bzltidy_tests/workspace/MODULE.bazel.lock, tests/bzltidy_tests/workspace/child_workspaces/bar/MODULE.bazel.lock, tests/bzltidy_tests/workspace/child_workspaces/foo/MODULE.bazel.lock
The `MODULE.bazel.lock` file can change between Bazel versions. Hence, the `:tidy_modified` test can only pass on a single Bazel version. The PR updates the test to work with 7.0.0.rc4.
Closes #371.
=> fix: only run bzltidy tests for a single Bazel version

bzlrelease/tools/generate_release_notes.sh, tests/bzlrelease_tests/tools_tests/generate_release_notes_test.sh
The output of the GitHub API changed. Updated the script to account for the changes.
=> fix: generate release notes test

.bcr/presubmit.yml, .github/workflows/ci.yml, ci/tools/generate_ci_workflow/internal/github/workflow.go, tests/bzlrelease_tests/rules_tests/generate_release_notes_tests/generate_release_notes_test.sh
- Apply the generate_release_notes_test fix again.
- Add `workflow_dispatch` to the CI workflow.
=> fix: add Bazel version to the `run_tests` section of BCR presubmit

MODULE.bazel, doc/bazeldoc/build_rules_overview.md, doc/bazeldoc/providers.md, doc/bzlformat/rules_and_macros_overview.md, doc/bzllib/bazel_labels.md, doc/bzllib/filter_srcs.md, doc/bzllib/lists.md, doc/bzllib/src_utils.md, doc/bzlrelease/create_release.md, doc/bzlrelease/generate_release_notes.md, doc/bzlrelease/generate_workspace_snippet.md, doc/bzlrelease/hash_sha256.md, doc/bzlrelease/release_archive.md, doc/bzlrelease/update_readme.md, doc/bzltidy/rules_and_macros_overview.md, doc/shlib/execute_binary.md, doc/updatesrc/providers_overview.md, doc/updatesrc/rules_and_macros_overview.md, doc/updatesrc/update_srcs.md
Upgrade stardoc to support doc generation for bzlmod extensions. I had issues upgrading all the way to 0.7.0.
=> chore: upgrade stardoc to 0.6.2

.github/workflows/ci.yml, doc/updatesrc/rules_and_macros_overview.md, updatesrc/private/updatesrc_diff_and_update.bzl
When using `updatesrc_diff_and_update` there will be a corresponding `update` target which should be run if
the files differ.
=> Provide a helpful message what to do if diff fails

BUILD.bazel, MODULE.bazel, bzlrelease/tools/create_release.sh, bzlrelease/tools/create_release_tag.sh, bzlrelease/tools/generate_gh_changelog.sh, shlib/lib/BUILD.bazel, shlib/lib/github.sh, tests/shlib_tests/lib_tests/github_tests/get_gh_auth_status_test.sh, tests/shlib_tests/lib_tests/github_tests/get_gh_changelog_test.sh, tools/gh/BUILD.bazel, tools/gh/multitool.lock.json
Addresses issues where `gh` could not be found in `rules_bazel_integration_test` tests.
=> fix: use `rules_multitool` to use GitHub CLI (gh)

MODULE.bazel, bzlrelease/private/BUILD.bazel, bzlrelease/private/release_archive.bzl, tests/bzlrelease_tests/rules_tests/release_artifact_tests/BUILD.bazel, tests/bzlrelease_tests/rules_tests/release_artifact_tests/archive_test.sh, tools/tar/BUILD.bazel, tools/tar/tar_binary.bzl, tools/tar/tar_toolchains.bzl
- Use [BSD tar toolchain](https://github.com/bazel-contrib/bazel-lib/blob/main/lib/private/tar_toolchain.bzl) for release archive functionality.
- Define `//tools/tar` target.
=> feat: use BSD tar toolchain for release archive functionality

.bcr/presubmit.yml
=> fix: sync Bazel version for BVCR presubmit

shlib/lib/arrays.sh, tests/shlib_tests/lib_tests/arrays_tests/sort_items_test.sh
Address subtle sort differences seen when sorting uppercase and lowercase paths on MacOs vs Linux. Setting `LC_ALL=C` ensures that byte order is used.
=> fix: set `LC_ALL=C` when using `sort`

.github/workflows/ci.yml, MODULE.bazel, examples/bzlmod_e2e/MODULE.bazel, examples/tools/workspace/MODULE.bazel, examples/updatesrc/simple/MODULE.bazel
- Upgrade `aspect_bazel_lib` to 2.19.4 to address https://github.com/cgrindel/swift_gazelle_plugin/issues/86#issuecomment-3016813840.
- Upgrade `platforms` to 0.0.11 to address build warning.
Related to #525.
=> chore: upgrade `aspect_bazel_lib` to 2.19.4
